### ISSUE TITLE
Do you have a translation file for traditional Chinese characters?

### ISSUE THREAD

**Issue by zackxu1** [onomojo/i18n-country-translations#12]
Hi.

Great gem, thanks.

I see you have a zh.yml for Chinese.  But as you may be aware, there're 2 versions of Chinese: traditional Chinese and simplified Chinese.

Simplified Chinese is used in China.
Traditional Chinese is used in Hong Kong and Taiwain.

Do you have a traditional Chinese file?
Thanks
Zack

**Comment by buhtz** [comment]
Dear @zackxu1 ,
my apologize for contacting you this way but I wasn't able to find a email address or something else.

I assume you are a native "speaker" of Traditional Chinese, right?

I'm looking for a translation of a [100 words text](https://translate.codeberg.org/translate/backintime/common/zh_Hant/?q=hello) into Traditional Chinese in the context of a backup software named [Back In Time](https://github.com/bit-team/backintime). The text is addressed to the users and tries to attract them contributing to the translation of the software they use them self.

Can you help us out here?
