### ISSUE TITLE
`'NO': ` vs `NO:`

### ISSUE THREAD

**Issue by sophiedeziel** [onomojo/i18n-country-translations#35]
Is there a specific reason why Norway's code is a string instead of a symbol in each yml file?

**Comment by onomojo** [comment]
Its been a while but I believe it was because rails or yml didn't like NO for some reason as a symbol. It was turning the NO into something else before parsing it so Norway would never show up and it'd get some weird crash from it.

**Comment by lazyatom** [comment]
This is because YAML parses `"no"` as `false`:

```ruby
YAML.load("no") # => false
```

**Comment by onomojo** [comment]
Closing this since we've gotta keep it quoted
